version: '3'
services:
  helloworld:
    image: adrien027/helloworld:1.0
  web-nginx:
    image: adrien027/web-ngix:1.0
    ports:
    - "5001:80"
  cat:
    image: adrien027/cat:1.0
    ports:
    - "5000:5000"
  


